jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      NODE_VERSION: 10.15.3
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true

    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - task: NodeTool@0
        inputs:
          versionSpec: '10.15.3'
        displayName: 'TOOLS: install Node.js'
      - script: sudo npm install -g npm
        displayName: 'TOOLS: update NPM'
      - script: sudo chown -R vsts:docker /home/vsts/.npm/
        displayName: 'BUGS-FIX: change /home/vsts/.npm/ permission'
      - script: sudo /etc/init.d/mysql stop
        displayName: 'TOOLS: stop MySQL'
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      - script: npm install
        displayName: 'INSTALL: launch npm install'
      - script: |
          chmod +x mvnw
          ./mvnw clean verify
        displayName: 'TESTS: backend'
      - script: ./mvnw com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run test'
        displayName: 'TESTS: frontend'
      - script: ./mvnw verify -Pprod -DskipTests
        displayName: 'TESTS: packaging'
      #----------------------------------------------------------------------
      # Production build
      #----------------------------------------------------------------------
      - script: ./mvnw package -Pprod -DskipTests
        displayName: 'BUILD: creating production build'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'target'
          Contents: '*.jar'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: bugtracker
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Azure for Students(ebe0e043-9daa-42f3-976c-bcea78c9a2b9)'
          appType: 'webAppLinux'
          WebAppName: 'spring-on-azure'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
          RuntimeStack: 'JAVA|11-java11'
          StartupCommand: 'java -jar app.jar'